---

- name: Create repos
  copy: src={{ item }} dest=/etc/yum.repos.d
  with_items:
    - epel.repo
    - rpmforge.repo
  tags:
    - common

- name: Create GPG keys for repos
  copy: src={{ item }} dest=/etc/pki/rpm-gpg
  with_items:
    - RPM-GPG-KEY-EPEL-6
    - RPM-GPG-KEY-rpmforge-dag
  tags:
    - common

- name: Install common packages
  yum: name={{ item }} state=latest enablerepo=rpmforge-extras,epel
  with_items:
    - git
    - python-devel
    - gcc
    - unzip
    - curl
    - wget
    - nc
  tags:
    - common

- name: Install pip
  easy_install: name=pip
  tags:
    - common
