---

- name: Download Java Build Tools
  get_url: url={{ item }} dest=/tmp/
  with_items:
    - http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.2-bin.zip
    - http://archive.apache.org/dist/ant/binaries/apache-ant-1.8.4-bin.zip
    - http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.7.zip
    - http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.2.4.zip
    - http://dist.groovy.codehaus.org/distributions/groovy-binary-1.8.9.zip
    - http://archive.apache.org/dist/maven/binaries/apache-maven-3.1.1-bin.zip
    - http://services.gradle.org/distributions/gradle-1.8-bin.zip
  tags:
    - java_build

- name: Unzip Java Build Tools
  shell: /usr/bin/unzip -o {{ item }} -d /opt/
  with_items: 
    - /tmp/apache-ant-1.9.2-bin.zip
    - /tmp/apache-ant-1.8.4-bin.zip
    - /tmp/grails-1.3.7.zip
    - /tmp/grails-2.2.4.zip
    - /tmp/groovy-binary-1.8.9.zip
    - /tmp/apache-maven-3.1.1-bin.zip
    - /tmp/gradle-1.8-bin.zip
  tags:
    - java_build