---

- name: Download Java Build Tools
  get_url: url={{ item }} dest=/tmp/
  with_items:
    - http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.2-bin.zip
    - http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-1.3.7.zip
    - http://archive.apache.org/dist/maven/binaries/apache-maven-3.1.1-bin.zip
  register: results
  tags:
    - java_build

- name: Unzip Java Build Tools
  shell: /usr/bin/unzip -o {{ item }} -d /opt/
  with_items: 
    - /tmp/apache-ant-1.9.2-bin.zip
    - /tmp/grails-1.3.7.zip
    - /tmp/apache-maven-3.1.1-bin.zip
  when: results.changed
  tags:
    - java_build
