---

- name: Ensure the app server is started before attempting to shut it down
  wait_for: port=8005
  tags:
    - ozone_app
    - ozone_app_config
    - ozone_app_war

- name: Stop the app server
  service: state=stopped name=tomcat
  tags:
    - ozone_app
    - ozone_app_config
    - ozone_app_war

- name: Ensure elastic search index location exists if needed
  file: state=directory
        path=/opt/ozone_store/searchable-index/
        owner=tomcat
        group=tomcat
        mode=0660
  when: {{ ozone_app_name }} is 'mp'
  tags:
    - ozone_app

- name: Install security context configuration
  template: src={{ app_security_context[ozone_app_name].file }}
            dest=/usr/share/tomcat/lib/{{ app_properties[ozone_app_name].security_file }}
            owner=tomcat
            group=tomcat
            mode=0660
  tags:
    - ozone_app
    - ozone_app_config

- name: Install external application configuration
  template: src=Config.groovy
            dest=/usr/share/tomcat/lib/{{ app_properties[ozone_app_name].external_config_file }}
            owner=tomcat
            group=tomcat
            mode=0660
  tags:
    - ozone_app
    - ozone_app_config

- name: Install Ozone configuration
  template: src=OzoneConfig.properties
            dest=/usr/share/tomcat/lib/OzoneConfig.properties
            owner=tomcat
            group=tomcat
            mode=0660
  tags:
    - ozone_app
    - ozone_app_config

- name: Install ehcache configuration
  template: src=ehcache.xml
            dest=/usr/share/tomcat/lib/ehcache.xml
            owner=tomcat
            group=tomcat
            mode=0660
  tags:
    - ozone_app
    - ozone_app_config

- name: Ensure the app server is stopped before replacing the war file
  wait_for: state=stopped port=8005
  tags:
    - ozone_app
    - ozone_app_war
    - ozone_app_config

- name: Register list of files in the webapps directory
  command: ls -1 /usr/share/tomcat/webapps
  register: webapp_files
  tags:
    - ozone_app
    - ozone_app_war

- name: Remove the webapp files
  file: state=absent path=/usr/share/tomcat/webapps/{{ item }}
  with_items: webapp_files.stdout_lines
  tags:
    - ozone_app
    - ozone_app_war

- name: Install the ozone app war file from local filesystem
  get_url: url=ozone_app_war_url
       dest=/usr/share/tomcat/webapps/{{ app_properties[ozone_app_name].default_context }}.war
       owner=tomcat
       group=tomcat
       mode=0644
  tags:
    - ozone_app
    - ozone_app_war

- name: Start the app server
  service: state=started name=tomcat
  tags:
    - ozone_app
    - ozone_app_war
    - ozone_app_config

- name: Ensure the app server is started before continuing
  wait_for: port=8005
  tags:
    - ozone_app
    - ozone_app_war
    - ozone_app_config
