---

- name: Install OpenJDK Packages for Java 6 and 7
  yum: name={{ item }} state=present
  with_items:
    - java-1.6.0-openjdk
    - java-1.7.0-openjdk
  tags:
    - jre

- name: Set Java 6 as the current jre
  shell: alternatives --set java /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java
  when: java_version == 6
  tags:
    - jre

- name: Set Java 7 as the current jre
  shell: alternatives --set java /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java
  when: java_version == 7
  tags:
    - jre
