---

- name: Setup the Ozone Build Environment
  hosts: 127.0.0.1
  user: "{{ ansible_local.ozone.user }}"
  sudo: yes
  roles:
    - ../roles/common
    - role: ../roles/jdk
      jdk_version: 6
    - ../roles/build_java
    - ../roles/build_css
    - ../roles/build_js
