---

- name: Setup the Ozone Build Environment
  hosts: 127.0.0.1
  user: "{{ ansible_user }}"
  sudo: yes
  roles:
    - ../roles/common
    - role: ../roles/jre
      java_version: 6
    - role: ../roles/jdk
      java_version: 6
    - ../roles/build_java
    - ../roles/build_css
    - ../roles/build_js
    - ../roles/tomcat7
