---

- name: Install OpenJDK Packages for Java 6 and 7
  yum: name={{ item }} state=present
  with_items:
    - java-1.6.0-openjdk-devel
    - java-1.7.0-openjdk-devel
  tags:
    - jdk

- name: Set Java 6 as the current jdk
  shell: alternatives --set javac /usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/javac
  when: java_version == 6
  tags:
    - jdk

- name: Set Java 7 as the current jdk
  shell: alternatives --set javac /usr/lib/jvm/java-1.7.0-openjdk.x86_64/bin/javac
  when: java_version == 7
  tags:
    - jdk
