---

- include: setup_groups.yml

- name: Create EC2 Instances
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: ../roles/ec2
      ec2_instance_tags: '{"Name": "Jenkins CI Server"}'
      ec2_groups: 'commonRules,appServers'
      ansible_host_group: transient_ci_servers
    - role: ../roles/ec2
      ec2_instance_tags: '{"Name": "Ozone Build Server"}'
      ec2_groups: 'commonRules'
      ec2_count: 4
      ansible_host_group: transient_build_servers

- name: Setup Jenkins CI Servers
  hosts: transient_ci_servers
  user: ec2-user
  sudo: yes
  roles:
    - ../roles/common
    - ../roles/ansible
    - ../roles/mysql_client
    - role: ../roles/jdk
      jdk_version: 6
    - ../roles/build_java
    - ../roles/build_css
    - ../roles/build_js
    - ../roles/jenkins
    - ../roles/httpd

- name: Setup Jenkins Build Nodes
  hosts: transient_build_servers
  user: ec2-user
  sudo: yes
  roles:
    - ../roles/common
    - ../roles/ansible
    - ../roles/mysql_client
    - role: jdk
      jdk_version: 6
    - ../roles/build_java
    - ../roles/build_css
    - ../roles/build_js
