---

- name: Create EC2 Instances
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: ../roles/ec2
      ec2_instance_tags: '{"Name": "amlmp", "aml_env": "perf01"}'
      ec2_groups: ['aml_common', 'aml_tomcat_server']
      ec2_instance_type: m1.small
      ansible_host_group: transient_ozone_app

- name: Setup a tomcat server
  hosts: transient_ozone_app
  user: ec2-user
  sudo: yes
  roles:
    - ../roles/common
    - role: ../roles/jre
      java_version: 6
    - ../roles/tomcat7
    - role: ../roles/ozoneapp
      app_url: 'http://amlci01.goss.owfgoss.org:8080/jenkins/view/wars/job/war-franchise-store/lastSuccessfulBuild/artifact/target/marketplace.war' 
      app_name: 'mp'
